### ISSUE TITLE
Manifest merge failed

### ISSUE THREAD

**Issue by QiiqeAzuara** [HussainDerry/secure-preferences#1]
Hi! Nice work , but you should not set attribute application@allowbackup value=(true).

- allowBackup = true/false : the app's data can be backup or not.
You should let the app that use your lib will decide whether its data can be backup or not.

"tools:replace" is necessary in this case.

**Comment by HussainDerry** [comment]
Hi, Thanks for the heads-up, the attribute has been removed from the manifest in the new version '0.0.3', so I believe the issue is resolved now.
